services:
  postgres:
    image: postgres:17-alpine
    container_name: shipublic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shipublic
      POSTGRES_PASSWORD: shipublic
      POSTGRES_DB: shipublic
    ports:
      - "5433:5432"
    volumes:
      - shipublic_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shipublic_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - shipublic_redis:/data

volumes:
  shipublic_pg:
  shipublic_redis:
